### ISSUE TITLE
HTTP Panic

### ISSUE THREAD

**Issue by hazrulnizam** [believethehype/nostdress#2]
OS: `Linux 5.4.17-2136.316.7.el8uek.x86_64`
Satdress version: `v.0.8.6.4`

Steps to reproduce:

1. Download and extract compiled binary from Github releases page.
2. `$ export PORT=3000`
`$ export DOMAIN=hazrulnizam.com`
`$ export SECRET=secret`
`$ export SITE_OWNER_URL=https://hazrulnizam.com`
`$ export SITE_OWNER_NAME=@hazrul`
`$ export SITE_NAME=Satdress`
`$ export NOSTR_PRIVATE_KEY=nsec<redacted>`
`$ export NIP05=true`
`$ ./satdress`

3. Go to `http://<IP_address>:3000/lnaddress`:

![Capture1](https://user-images.githubusercontent.com/47681422/225380884-f16cd2fb-68c9-4573-91bc-65bd870685ef.PNG)

4. The Success page shows up and a lightning invoice of 1 sat is created.
5. At this point, `http://<IP_address>:3000/.well-known/nostr.json` works with the following response:
```
{
  "names": {
	"sats": "60583b61578fa8e9148dd49d4a1aa08c9a10f8290491979bd48e7639c07adb86"
 	}
}
```

6. But trying to GET `http://<IP_address>:3000/.well-known/lnurlp/sats` gives `ERR_EMPTY_RESPONSE` and the following shows up in the console:

```
<nil> INF got lnurl request domain=hazrulnizam.com username=sats
2023/03/16 00:50:35 http: panic serving <redacted>:51905: runtime error: index out of range [0] with length 0
goroutine 41 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0xe70300, 0xc00054e000})
        /usr/local/go/src/runtime/panic.go:890 +0x263
main.GetNostrProfileMetaData({0xc000142500, 0x3f})
        /github/workspace/nostr.go:122 +0x746
main.metaData(0xc00041e410)
        /github/workspace/invoice.go:27 +0x1c6
main.handleLNURL({0x10c7f40?, 0xc00016c0e0}, 0xc000171900)
        /github/workspace/lnurl.go:130 +0x505
net/http.HandlerFunc.ServeHTTP(0xc000171800?, {0x10c7f40?, 0xc00016c0e0?}, 0xc0000a8301?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000184300, {0x10c7f40, 0xc00016c0e0}, 0xc000171700)
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x10c7f40, 0xc00016c0e0}, 0xc000171700)
        /go/pkg/mod/github.com/rs/cors@v1.8.3/cors.go:236 +0x1c4
net/http.HandlerFunc.ServeHTTP(0x0?, {0x10c7f40?, 0xc00016c0e0?}, 0x47500e?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.serverHandler.ServeHTTP({0xc0002e4720?}, {0x10c7f40, 0xc00016c0e0}, 0xc000171700)
        /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0000a4120, {0x10c8978, 0xc0002e5410})
        /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x5ed
```

--------------

I tried compiling from source and it gives the same error.

For information, I have been using the original Satdress without issues. I was interested to try experiment enabling Zaps for my nostr so I came across your fork.

Thanks!

**Comment by believethehype** [comment]
Hi, thank you for the feedback. Can you try v.0.8.6.6? By default grabbing of Nostr profile pictures is now disabled (which seems to have caused problems for you). Not quite sure what causes the errors. Please let me know if this works for you.

**Comment by hazrulnizam** [comment]
I tried 0.8.6.6 and it works! Thanks!

`<nil> DBG Nostr ZAPPED ⚡️="Published zap on Nostr"`
