### ISSUE TITLE
Feature request: List all registered users

### ISSUE THREAD

**Issue by hazrulnizam** [believethehype/nostdress#24]
Is there an easy way to query and list all registered users?

I understand the database backend is using [pebble](https://github.com/cockroachdb/pebble) but as a non-programmer it is a bit difficult to understand how to maneuver around the key-value data. Is there a client or CLI we can use to query the db? Or an API endpoint perhaps?

Thanks, you are doing a great job with this fork. Appreciate it.

**Comment by believethehype** [comment]
Hey, I added a new api command  {domain}/api/listUsers/ where you can list all existing users in the database. This will only work when the ALLOW_API is set to true.  (version 0.9.1.5)

**Comment by hazrulnizam** [comment]
Amazing! Thank you!
