### ISSUE TITLE
If ALLOW_API is false - docker container not started

### ISSUE THREAD

**Issue by Perlover** [believethehype/nostdress#25]
Hello,

I want to turn off API

I set `ALLOW_API=false` in docker-compose.yml but after this container is not run
If I set `ALLOW_API=true` then a container works again

**Comment by Perlover** [comment]
https://github.com/believethehype/nostdress/blob/master/main.go#L283

I think this and the following lines should be taken out for a condition that is worked out only when the API is enabled

**Comment by believethehype** [comment]
It's merged but the git autobuild seems to have problems currently

**Comment by believethehype** [comment]
We're so back.
