### ISSUE TITLE
BUG: Sends dm even if invoice is unpaid

### ISSUE THREAD

**Issue by f321x** [believethehype/nostdress#6]
Behaviour: 
When sending to my Satdress address fails I still get a Nostr DM saying I received sats. 

Expected behavior: 
Only get a DM if I get a successful payment to my lnaddress

**Comment by believethehype** [comment]
Can you give more details on that? What backend were you using? The code shouldn't allow this to happen at the moment.

**Comment by f321x** [comment]
In my case I used lnbits (legend.lnbits.com) as backend and tried to send my whole balance from Zebedee wallet (41 sat) to my lnaddress, this failed because I need 1 sat routing fees and could only send 40 sat out of Zebedee. In lnbits it showed the invoice as created but unpaid (like it's supposed to). In Nostr I still got the DM:
"Received Non-Zap! Amount: 41 Sats ⚡️. Comment: Cash Out to x@lnaddress.com" (these 41 sats never entered my wallet).

**Comment by believethehype** [comment]
Ok, yes, invoices of non-zaps are currently not checked on their paid status. This needs to be added. For zaps this shouldnt happen tho.

**Comment by believethehype** [comment]
should be fixed in v.0.9.0.2

**Comment by f321x** [comment]
Machine🙏

**Comment by believethehype** [comment]
(it's still building)
