### ISSUE TITLE
Wrong UI: shows nip05 field even if deactivated

### ISSUE THREAD

**Issue by f321x** [believethehype/nostdress#7]
Behaviour:
I set nip05 to false in env settings but the Satdress interface still shows the input field as "Nostr npub (optional for NIP05)" to input the npub (which is necessary for dm's)

Expected behavior:
Don't show the "(optional for NIP05)" if nip05 is deactivated and maybe show "(for DM notification)" on the npub input field to prevent user confusion. Otherwise users maybe expect a working nip05 identifier which then doesn't work

![Screenshot_20230408-191550_1](https://user-images.githubusercontent.com/51097237/230734405-9797939a-4c5d-4995-9b0c-242db3fb2e19.png)

**Comment by believethehype** [comment]
Changed it to a more generic "For Nostr services"
